services:
  brzez_access_policy.access_policy_provider:
    class: Brzez\AccessPolicyBundle\Service\ContainerAware\ContainerAwareAccessPolicyProvider
    arguments: []
    calls:
      - [ setContainer, [ '@service_container' ] ]
  brzez_access_policy.twig_ext:
    class: Brzez\AccessPolicyBundle\Twig\Extension\AccessCheckerExtension
    arguments: ['@brzez_access_policy.access_policy_provider']
    public: false
    tags:
      - {name: twig.extension}
       
