services:
  brzez_access_policy.access_policy_provider:
    class: Brzez\AccessPolicyBundle\Service\ContainerAware\ContainerAwareAccessPolicyProvider
    arguments: []
     # arguments: ["@service_id", "plain_value", %parameter%]
    calls:
      - [ setContainer, [ '@service_container' ] ]
       
